var dic =
    {
        AREA: "面积",
        NAME: "名称",


        //CCWJQ
        BSM: "标识码",
        YSDM: "要素代码",
        ZDMJ: "占地面积",
        BZ: "备注",

        //CJDCQJX
        BSM: "标识码",
        YSDM: "要素代码",
        JXLX: "界线类型",
        JXXZ: "界线性质",
        JXSM: "界线说明",
        BZ: "备注",

        //CJDCQJX
        BSM: "标识码",
        YSDM: "要素代码",
        JXLX: "界线类型",
        JXXZ: "界线性质",
        JXSM: "界线说明",
        BZ: "备注",

        //CZCDYD
        BSM: "标识码",
        YSDM: "要素代码",
        CZCLX: "城镇村等用地类型",
        CZCDM: "城镇村代码",
        CZCMC: "城镇村名称",
        CZCMJ: "城镇村面积",
        BZ: "备注",

        //DLTB
        BSM: "标识码",
        YSDM: "要素代码",
        TBYBH: "图斑预编号",
        TBBH: "图斑编号",
        DLBM: "地类编码",
        DLMC: "地类名称",
        QSXZ: "权属性质",
        QSDWDM: "权属单位代码",
        QSDWMC: "权属单位名称",
        ZLDWDM: "坐落单位代码",
        ZLDWMC: "坐落单位名称",
        TBMJ: "图斑面积",
        KCDLBM: "扣除地类编码",
        KCXS: "扣除地类系数",
        KCMJ: "扣除地类面积",
        TBDLMJ: "图斑地类面积",
        GDPDJB: "耕地坡度级别",
        GDLX: "耕地类型",
        XZDWKD: "线状地物宽度",
        TBXHDM: "图斑细化代码",
        TBXHMC: "图斑细化名称",
        ZZSXDM: "种植属性代码",
        ZZSXMC: "种植属性名称",
        GDDB: "耕地等别",
        FRDBS: "飞入地标识",
        CZCSXM: "城镇村属性码",
        SJNF: "数据年份",
        MSSM: "描述说明",
        BZ: "备注",
        HDMC: "海岛名称",

        // GJGY
        BSM: "标识码",
        YSDM: "要素代码",
        BHQMC: "保护区名称",
        BHQDLWZ: "保护区地理位置",
        BHQJB: "保护区级别",
        PZJG: "批准机关",
        PZSJ: "批准时间",
        BHQMJ: "保护区面积",
        BZ: "备注",

        //KFYQ
        BSM: "标识码",
        YSDM: "要素代码",
        KFYQMC: "开发园区名称",
        KFYQLX: "开发园区类型",
        KFYQXZ: "开发园区性质",
        KFYQTZ: "开发园区特征",
        KFYQMJ: "开发园区面积",
        BZ: "备注",

        //LSYD
        BSM: "标识码",
        YSDM: "要素代码",
        GLTBBSM: "关联图斑标识码",
        PZWJMC: "批准文件名称",
        PZWH: "批准文号",
        TBMJ: "图斑面积",
        PZMJ: "批准面积",
        YTFL: "用途分类",
        JTXMYT: "具体项目用途",
        PZRQ: "批准日期",
        BZ: "备注",

        //PDT
        BSM: "标识码",
        YSDM: "要素代码",
        PDJB: "坡度级别",
        BZ: "备注",

        //SDGY
        BSM: "标识码",
        YSDM: "要素代码",
        BHQMC: "保护区名称",
        BHQDLWZ: "保护区地理位置",
        BHQJB: "保护区级别",
        PZJG: "批准机关",
        PZSJ: "批准时间",
        BHQMJ: "保护区面积",
        BZ: "备注",

        //SLGY
        BSM: "标识码",
        YSDM: "要素代码",
        BHQMC: "保护区名称",
        BHQDLWZ: "保护区地理位置",
        BHQJB: "保护区级别",
        PZJG: "批准机关",
        PZSJ: "批准时间",
        BHQMJ: "保护区面积",
        BZ: "备注",

        //STBHHX
        BSM: "标识码",
        YSDM: "要素代码",
        XJXZQHDM: "县级行政区划代码",
        LXDM: "类型代码",
        SLDM: "数量代码",
        MC: "名称",
        RKSL: "人口数量",
        STGNYBHMB: "生态系统服务功能与保护目标",
        DLWZ: "地理位置",
        QYMJ: "区域面积",
        STXTYZBLX: "生态系统与植被类型",
        RWHDLX: "主要人为活动类型",
        STHJWT: "生态环境问题",
        GKCS: "管控措施",
        SLSJ: "设立时间",
        BZ: "备注",

        //TTQ
        BSM: "标识码",
        YSDM: "要素代码",
        TTQMJ: "推土区面积",
        BZ: "备注",

        //XZQJX
        BSM: "标识码",
        YSDM: "要素代码",
        JXLX: "界线类型",
        JXXZ: "界线性质",
        JXSM: "界线说明",
        BZ: "备注",

        //XZQ
        BSM : "标识码",
        YSDM : "要素代码",
        XZQDM : "行政区代码",
        XZQMC  : "行政区名称",
        DCMJ : "调查面积",
        JSMJ : "计算面积",
        MSSM : "描述说明",
        HDMC : "海岛名称",
        BZ : "备注",

        //YJJBNTTB
        BSM: "标识码",
        YSDM: "要素代码",
        JBNTTBBH: "基本农田图斑编号",
        TBBH: "图斑编号",
        DLBM: "地类编码",
        DLMC: "地类名称",
        QSXZ: "权属性质",
        QSDWDM: "权属单位代码",
        QSDWMC: "权属单位名称",
        ZLDWDM: "坐落单位代码",
        ZLDWMC: "坐落单位名称",
        GDLX: "耕地类型",
        KCLX: "扣除类型",
        KCDLBM: "扣除地类编码",
        TKXS: "扣除地类系数",
        XZDWMJ: "线状地物面积",
        LXDWMJ: "零星地物面积",
        TKMJ: "扣除地类面积",
        TBMJ: "基本农田图斑面积",
        JBNTMJ: "基本农田面积",
        JBNTLX: "基本农田类型",
        ZLDJDM: "质量等级代码",
        PDJB: "坡度级别",
        DLBZ: "地类备注",

        //ZRBHQ
        BSM: "标识码",
        YSDM: "要素代码",
        BHQMC: "保护区名称",
        BHQDLWZ: "保护区地理位置",
        BHQJB: "保护区级别",
        PZJG: "批准机关",
        PZSJ: "批准时间",
        BHQMJ: "保护区面积",
        BZ: "备注"
    }